version: '3'

env:
  PYTHON: /usr/bin/python3
  DEVICE: cuda:0

tasks:

  dependencies: 
    sources:
      - requirements.txt
    generates:
      - venv/.builded
    cmds:
      - rm -rf venv
      - $PYTHON -m venv venv
      - venv/bin/python3 -m pip install -r requirements.txt
      - touch venv/.builded

  ppo:
    deps: 
      - dependencies
    sources:
      - src/**/*.py
    generates:
      - models/ppo/.trained
    cmds:
      - mkdir -p models/ppo
      - venv/bin/python3 src/cli.py
        cli agent transformer-agent
        cli environment scattered
        cli loss ppo
        cli optimizer adam
        cli scheduler cosine
        cli trajectory ppo
        cli storage default
        cli logger file --path models/ppo/train.log
        cli callback base
        cli callback checkpointer --path models/ppo/agent.pkl 
        cli train 
      - touch models/ppo/.trained

  shac-learnable-reward:
    deps: 
      - dependencies
    sources:
      - src/**/*.py
    generates:
      - models/shac-learnable/.trained
    cmds:
      - mkdir -p models/shac-learnable
      - venv/bin/python3 src/cli.py
        cli agent transformer-agent --shared False --device $DEVICE
        cli environment scattered-learnable-reward --device $DEVICE
        cli loss shac
        cli optimizer adam
        cli scheduler cosine
        cli trajectory shac --device $DEVICE
        cli storage default
        cli logger file --path models/shac-learnable/train.log
        cli callback base-shac-learnable-reward
        cli callback checkpointer --path models/shac-learnable/agent.pkl 
        cli train 
      - touch models/shac-learnable/.trained



  ppo-learnable-reward:
    deps: 
      - dependencies
    sources:
      - src/**/*.py
    generates:
      - models/ppo-lernable/.trained
    cmds:
      - mkdir -p models/ppo-learnable
      - venv/bin/python3 src/cli.py
        cli agent transformer-agent
        cli environment scattered-learnable-reward
        cli loss ppo-learnable-reward
        cli optimizer adam
        cli scheduler cosine
        cli trajectory ppo
        cli storage default
        cli logger file --path models/ppo-learnable/train.log
        cli callback base-learnable-reward
        cli callback checkpointer --path models/ppo-learnable/agent.pkl 
        cli train
      - touch models/ppo-learnable/.trained


  fig:
    deps:
      - dependencies
    cmds:
      - jet init --shape 1 1
        jet line --samples 1000 --input-path models/ppo/train.log --x id --y message/reward --label ppo
        jet line --samples 1000 --input-path models/ppo-learnable-0/train.log --x id --y message/real_reward --label ppo-learnable
        jet line --samples 1000 --input-path models/ppo-learnable/train.log --x id --y message/real_reward --label ppo-learnable-2
        jet line --samples 1000 --input-path models/shac-learnable-0/train.log --x id --y message/real_reward --label shac-learnable-0
        jet line --samples 1000 --input-path models/shac-learnable/train.log --x id --y message/real_reward --label shac-learnable-1
        jet plot --show True

  clean-ppo:
    cmds:
      - rm -rf models/ppo
