version: '3'

env:
  PYTHON: /usr/bin/python3
  DEVICE: cuda:0

tasks:

  dependencies: 
    sources:
      - requirements.txt
    generates:
      - venv/.builded
    cmds:
      - rm -rf venv
      - $PYTHON -m venv venv
      - venv/bin/python3 -m pip install -r requirements.txt
      - touch venv/.builded

  ppo:
    deps: 
      - dependencies
    sources:
      - src/**/*.py
    generates:
      - models/ppo/.trained
    cmds:
      - mkdir -p models/ppo
      - venv/bin/python3 src/cli.py
        cli agent transformer-agent
        cli environment scattered
        cli loss ppo
        cli optimizer adam
        cli scheduler cosine
        cli trajectory ppo
        cli storage default
        cli logger file --path models/ppo/train.log
        cli callback base
        cli callback checkpointer --path models/ppo/agent.pkl 
        cli train 
      - touch models/ppo/.trained

  shac-learnable-reward:
    deps: 
      - dependencies
    sources:
      - src/**/*.py
    generates:
      - models/shac-learnable-reward/.trained
    cmds:
      - mkdir -p models/shac-learnable-reward
      - venv/bin/python3 src/cli.py
        cli agent transformer-agent
        cli environment scattered-learnable-reward
        cli environment reward transformer-reward
        cli loss shac
        cli optimizer adam
        cli scheduler cosine
        cli trajectory shac --device $DEVICE
        cli storage default
        cli logger file --path models/shac-learnable-reward/train.log
        cli callback base-shac-learnable-reward
        cli callback checkpointer --path models/shac-learnable-reward/agent.pkl 
        cli train 
      - touch models/shac-learnable-reward/.trained

  ppo-learnable-reward:
    deps: 
      - dependencies
    sources:
      - src/**/*.py
    generates:
      - models/ppo-lernable-reward/.trained
    cmds:
      - mkdir -p models/ppo-learnable-reward
      - venv/bin/python3 src/cli.py
        cli agent transformer-agent
        cli environment scattered-learnable-reward
        cli environment reward transformer-reward 
        cli loss ppo-learnable-reward
        cli optimizer adam
        cli scheduler cosine
        cli trajectory ppo
        cli storage default
        cli logger file --path models/ppo-learnable-reward/train.log
        cli callback base-learnable-reward
        cli callback checkpointer --path models/ppo-learnable-reward/agent.pkl 
        cli train
      - touch models/ppo-learnable-reward/.trained

  viz:
    deps: [dependencies]
    cmds:
      - venv/bin/python3 src/cli.py
        cli agent transformer-agent --state-dict-path models/ppo/agent.pkl
        cli environment scattered --envs 1
        cli viz --show True

  fig:
    deps:
      - dependencies
    cmds:
      - jet init --shape 1 1
        jet line --samples 1000 --input-path models/ppo/train.log                   --x id --y message/reward      --label ppo
        jet line --samples 1000 --input-path models/ppo-learnable-reward/train.log  --x id --y message/real_reward --label ppo-learnable-reward
        jet line --samples 1000 --input-path models/shac-learnable-reward/train.log --x id --y message/real_reward --label shac-learnable-reward
        jet plot --show True

  clean-ppo:
    cmds:
      - rm -rf models/ppo

