version: '3'

tasks:
  default:
    sources:
      - src/**/*.py
      - venv/bin/python3
    vars:
      FOLDER : '{{default "dispersion/shac/proxied" .FOLDER}}'
      DEVICE : '{{default "cuda:0" .DEVICE}}'
    generates:
      - models/{{.FOLDER}}/.trained
    cmds:
      - mkdir -p models/{{.FOLDER}}
      - venv/bin/python3 src/cli.py
        cli environment proxied dispersion --device {{.DEVICE}} 
                                           --envs 128 
                                           --agents 3 
                                           --seed 42 
                                           --requires-grad True
        cli environment proxied dispersion mlp --hidden-size 256 
                                               --layers 3 
                                               --dropout 0.0 
                                               --activation ReLU
        cli environment proxied dispersion optimizer adam --learning-rate 0.0001
        cli environment proxied dispersion scheduler constant
        cli agent mlp --compile True 
                      --hidden-size 128 
                      --layers 1
                      --shared False 
                      --critic-init-gain 1.41
                      --actor-init-gain  1.41
        cli algorithm shac --batch-size 1024 
                           --epochs 8 
                           --target-alpha 0.4
        cli algorithm shac critic-optimizer adam --learning-rate 0.001 
        cli algorithm shac actor-optimizer  adam --learning-rate 0.001 
        cli algorithm shac critic-scheduler constant  
        cli algorithm shac actor-scheduler  constant
        cli algorithm shac trajectory default --steps 32 --utr 5
        cli callback greeting
        cli callback barline
        cli callback proxied trainlog --path    models/{{.FOLDER}}/train.log
        cli callback checkpoint-agent --path    models/{{.FOLDER}}/agent.pkl --etc 100
        cli callback saveconfig       --path    models/{{.FOLDER}}/config.json
        cli callback proxied proxylog --path    models/{{.FOLDER}}/proxy.log
        cli callback proxied validate --sdpath  models/{{.FOLDER}}/best.pkl 
                                      --logpath models/{{.FOLDER}}/valid.log
                                      --etc 10 --size 512 --steps 64
        cli train --episodes {{.EPISODES}} --seed 42 
      - cp ./taskfile.yaml models/{{.FOLDER}}/
      - touch models/{{.FOLDER}}/.trained
