version: '3'

tasks:
  default:
    sources:
      - src/**/*.py
      - venv/bin/python3
    vars:
      FOLDER : '{{default "dispersion/ppo/default" .FOLDER}}'
      DEVICE : '{{default "cuda:0" .DEVICE}}'
    generates:
      - models/{{.FOLDER}}/.trained
    cmds:
      - mkdir -p models/{{.FOLDER}}
      - venv/bin/python3 src/cli.py
        cli environment dispersion --device {{.DEVICE}} 
                                   --envs 128 
                                   --agents 3 
                                   --seed 42 
                                   --requires-grad False
        cli agent mlp --compile True 
                      --hidden-size 128 
                      --layers 1
                      --shared True 
                      --critic-init-gain 1.41
                      --actor-init-gain 0.1
        cli algorithm ppo --batch-size 1024 
                          --epochs 8 
                          --batch-size 1024   
                          --max-grad-norm 0.5 
                          --epochs 4          
                          --clip-coef 0.2     
                          --vf-coef 0.5 
                          --ent-coef 0.0        
                          --vclip True        
        cli algorithm ppo optimizer adam --learning-rate 0.001 
        cli algorithm ppo scheduler constant
        cli algorithm ppo trajectory default --steps 32 --utr 5
        cli callback greeting
        cli callback barline
        cli callback trainlog         --path    models/{{.FOLDER}}/train.log
        cli callback checkpoint-agent --path    models/{{.FOLDER}}/agent.pkl --etc 100
        cli callback saveconfig       --path    models/{{.FOLDER}}/config.json
        cli callback validate --sdpath  models/{{.FOLDER}}/best.pkl 
                              --logpath models/{{.FOLDER}}/valid.log
                              --etc 10 --size 512 --steps 64
        cli train --episodes {{.EPISODES}} --seed 42 
      - cp ./taskfile.yaml models/{{.FOLDER}}/
      - touch models/{{.FOLDER}}/.trained
